"""
build_bvh_ext_win.py — Two-stage split build for bvh_router_ext.pyd

Same strategy as build_ternary_ext_win.py:
  Stage 1: nvcc compiles CUDA kernel into .obj — zero PyTorch headers
  Stage 2: MSVC compiles pybind11 wrapper into .obj — zero nvcc
  Stage 3: MSVC links both .obj files into bvh_router_ext.pyd

Resolves CUDA 13.2 CCCL vs PyTorch 2.11 cu128 header namespace conflicts.
"""

import os
import sys
import site
import subprocess
import textwrap
from pathlib import Path

# =============================================================================
# PATHS — must match build_ternary_ext_win.py
# =============================================================================

VCVARSALL    = r"C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"
CUDA_HOME    = r"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.2"
TORCH_HOME   = os.environ.get("TORCH_HOME", os.path.join(site.getsitepackages()[0], "torch"))  # Auto-detect torch location
PYTHON_HOME  = r"C:\Python314"
SM_ARCH      = "sm_120"
COMPUTE_ARCH = "compute_120"

EXT_NAME = "bvh_router_ext"

# =============================================================================
# Derived paths
# =============================================================================

SCRIPT_DIR   = Path(__file__).parent.resolve()
BUILD_DIR    = SCRIPT_DIR / "build_bvh"
NVCC         = Path(CUDA_HOME) / "bin" / "nvcc.exe"

PYTHON_INC   = Path(PYTHON_HOME) / "include"
TORCH_INC    = Path(TORCH_HOME) / "include"
TORCH_INC_TH = Path(TORCH_HOME) / "include" / "torch" / "csrc" / "api" / "include"
CUDA_INC     = Path(CUDA_HOME) / "include"
TORCH_LIB    = Path(TORCH_HOME) / "lib"
PYTHON_LIB   = Path(PYTHON_HOME) / "libs"

KERNELS_CU   = BUILD_DIR / "bvh_kernels_only.cu"
WRAPPER_CPP  = BUILD_DIR / "bvh_pybind_wrapper.cpp"
KERNELS_OBJ  = BUILD_DIR / "bvh_kernels_only.obj"
WRAPPER_OBJ  = BUILD_DIR / "bvh_pybind_wrapper.obj"
PYD_OUT      = SCRIPT_DIR / f"{EXT_NAME}.pyd"

# =============================================================================
# Stage 0: Generated source files
# =============================================================================

KERNELS_CU_SOURCE = textwrap.dedent(r"""
    /*
     * bvh_kernels_only.cu
     * AUTO-GENERATED by build_bvh_ext_win.py — DO NOT EDIT
     *
     * Pure CUDA: NO PyTorch headers, NO pybind11.
     * Exports extern "C" launcher functions for the pybind11 wrapper.
     */

    #include <cuda_runtime.h>
    #include <stdint.h>

    #define BVH_BF            4
    #define BVH_LEVELS        3
    #define BVH_LEAVES       64
    #define BVH_NODES        85
    #define BVH_LEAF_OFFSET  21
    #define RAY_DIM           3
    #define SPEC_DIM         64
    #define PORTAL_SIZE      12
    #define WARP_SZ          32
    #define MAX_BATCH       1024

    #define ETA_MIN          0.5f
    #define ETA_MAX          2.0f
    #define ETA_RANGE        1.5f
    #define BAND_F0          0.000f
    #define BAND_F1          0.250f
    #define BAND_F2          0.500f
    #define BAND_F3          0.750f

    // =========================================================================
    // CONSTANT MEMORY
    // =========================================================================

    __constant__ float c_centers[BVH_NODES * 3];
    __constant__ float c_radii[BVH_NODES];
    __constant__ float c_portals[BVH_NODES * PORTAL_SIZE];
    __constant__ float c_snell_w[BVH_NODES * SPEC_DIM];
    __constant__ float c_snell_b[BVH_NODES];

    // =========================================================================
    // Device helpers
    // =========================================================================

    __device__ __forceinline__ float fast_sigmoid(float x) {
        return 1.0f / (1.0f + __expf(-x));
    }

    __device__ __forceinline__ float ray_sphere_dist_fused(
        float ox, float oy, float oz,
        float dx, float dy, float dz,
        float cx, float cy, float cz
    ) {
        float ocx = cx - ox, ocy = cy - oy, ocz = cz - oz;
        float t = __fmaf_rn(ocx, dx, __fmaf_rn(ocy, dy, ocz * dz));
        float px = __fmaf_rn(t, dx, ox) - cx;
        float py = __fmaf_rn(t, dy, oy) - cy;
        float pz = __fmaf_rn(t, dz, oz) - cz;
        return __fmaf_rn(px, px, __fmaf_rn(py, py, pz * pz));
    }

    __device__ __forceinline__ void argmin4(
        float d0, float d1, float d2, float d3,
        float& best_dist, int& best_idx
    ) {
        float  ab_d = (d0 <= d1) ? d0 : d1;
        int    ab_i = (d0 <= d1) ? 0  : 1;
        float  cd_d = (d2 <= d3) ? d2 : d3;
        int    cd_i = (d2 <= d3) ? 2  : 3;
        best_dist = (ab_d <= cd_d) ? ab_d : cd_d;
        best_idx  = (ab_d <= cd_d) ? ab_i : cd_i;
    }

    __device__ __forceinline__ void apply_portal_parallel(
        float& ox, float& oy, float& oz,
        float& dx, float& dy, float& dz,
        int node_idx, int tid
    ) {
        if (tid < 3) {
            const float* p = &c_portals[node_idx * PORTAL_SIZE + tid * 4];
            float p0 = p[0], p1 = p[1], p2 = p[2], p3 = p[3];
            float new_o = __fmaf_rn(p0, ox, __fmaf_rn(p1, oy, __fmaf_rn(p2, oz, p3)));
            float new_d = __fmaf_rn(p0, dx, __fmaf_rn(p1, dy, p2 * dz));
            float no_x = __shfl_sync(0xFFFFFFFF, new_o, 0);
            float no_y = __shfl_sync(0xFFFFFFFF, new_o, 1);
            float no_z = __shfl_sync(0xFFFFFFFF, new_o, 2);
            float nd_x = __shfl_sync(0xFFFFFFFF, new_d, 0);
            float nd_y = __shfl_sync(0xFFFFFFFF, new_d, 1);
            float nd_z = __shfl_sync(0xFFFFFFFF, new_d, 2);
            ox = no_x; oy = no_y; oz = no_z;
            dx = nd_x; dy = nd_y; dz = nd_z;
        } else {
            float dummy_o = 0.0f, dummy_d = 0.0f;
            float no_x = __shfl_sync(0xFFFFFFFF, dummy_o, 0);
            float no_y = __shfl_sync(0xFFFFFFFF, dummy_o, 1);
            float no_z = __shfl_sync(0xFFFFFFFF, dummy_o, 2);
            float nd_x = __shfl_sync(0xFFFFFFFF, dummy_d, 0);
            float nd_y = __shfl_sync(0xFFFFFFFF, dummy_d, 1);
            float nd_z = __shfl_sync(0xFFFFFFFF, dummy_d, 2);
            ox = no_x; oy = no_y; oz = no_z;
            dx = nd_x; dy = nd_y; dz = nd_z;
        }
        float inv_norm = rsqrtf(__fmaf_rn(dx, dx, __fmaf_rn(dy, dy, dz * dz)) + 1e-12f);
        dx *= inv_norm; dy *= inv_norm; dz *= inv_norm;
    }

    __device__ __forceinline__ void snell_refract_parallel(
        float& spec_a, float& spec_b,
        int tid, int node_idx,
        float& confidence, float best_dist
    ) {
        int idx_a = tid;
        int idx_b = tid + WARP_SZ;
        float wa = c_snell_w[node_idx * SPEC_DIM + idx_a];
        float wb = c_snell_w[node_idx * SPEC_DIM + idx_b];
        float partial = __fmaf_rn(wa, spec_a, wb * spec_b);

        #pragma unroll
        for (int offset = WARP_SZ / 2; offset > 0; offset >>= 1) {
            partial += __shfl_down_sync(0xFFFFFFFF, partial, offset);
        }
        float dot_val = __shfl_sync(0xFFFFFFFF, partial, 0);
        float eta = fast_sigmoid(dot_val + c_snell_b[node_idx]);
        eta = __fmaf_rn(eta, ETA_RANGE, ETA_MIN);
        float inv_eta = __frcp_rn(eta);
        float eta_diff = inv_eta - eta;

        float band_a;
        switch (idx_a & 3) {
            case 0: band_a = BAND_F0; break;
            case 1: band_a = BAND_F1; break;
            case 2: band_a = BAND_F2; break;
            default: band_a = BAND_F3; break;
        }
        spec_a *= __fmaf_rn(band_a, eta_diff, eta);
        spec_b *= __fmaf_rn(band_a, eta_diff, eta);

        if (tid == 0) {
            confidence *= __expf(-best_dist);
        }
        confidence = __shfl_sync(0xFFFFFFFF, confidence, 0);
    }

    // =========================================================================
    // KERNEL — bvh_router_fused_kernel_v2
    // =========================================================================

    __global__ void __launch_bounds__(WARP_SZ, 32)
    bvh_router_fused_kernel(
        const float* __restrict__ ray_origins,
        const float* __restrict__ ray_directions,
        const float* __restrict__ ray_spectral,
        int* __restrict__   out_expert,
        float* __restrict__ out_scores,
        int* __restrict__   out_path,
        float* __restrict__ out_confidence,
        const int batch_size
    ) {
        const int sample = blockIdx.x;
        if (sample >= batch_size) return;
        const int tid = threadIdx.x;

        float ox, oy, oz, dx, dy, dz;
        if (tid == 0) {
            const int base = sample * 3;
            ox = __ldg(&ray_origins[base]);
            oy = __ldg(&ray_origins[base + 1]);
            oz = __ldg(&ray_origins[base + 2]);
            dx = __ldg(&ray_directions[base]);
            dy = __ldg(&ray_directions[base + 1]);
            dz = __ldg(&ray_directions[base + 2]);
        }
        ox = __shfl_sync(0xFFFFFFFF, ox, 0);
        oy = __shfl_sync(0xFFFFFFFF, oy, 0);
        oz = __shfl_sync(0xFFFFFFFF, oz, 0);
        dx = __shfl_sync(0xFFFFFFFF, dx, 0);
        dy = __shfl_sync(0xFFFFFFFF, dy, 0);
        dz = __shfl_sync(0xFFFFFFFF, dz, 0);

        const float orig_ox = ox, orig_oy = oy, orig_oz = oz;
        const float orig_dx = dx, orig_dy = dy, orig_dz = dz;

        float spec_a = __ldg(&ray_spectral[sample * SPEC_DIM + tid]);
        float spec_b = __ldg(&ray_spectral[sample * SPEC_DIM + tid + WARP_SZ]);

        int current_node = 0;
        float confidence = 1.0f;

        #pragma unroll
        for (int level = 0; level < BVH_LEVELS; level++) {
            int first_child = current_node * BVH_BF + 1;

            float d0, d1, d2, d3;
            {
                int c0 = first_child, c1 = first_child + 1;
                int c2 = first_child + 2, c3 = first_child + 3;

                d0 = ray_sphere_dist_fused(ox, oy, oz, dx, dy, dz,
                         c_centers[c0*3], c_centers[c0*3+1], c_centers[c0*3+2])
                     - c_radii[c0] * c_radii[c0];
                d1 = ray_sphere_dist_fused(ox, oy, oz, dx, dy, dz,
                         c_centers[c1*3], c_centers[c1*3+1], c_centers[c1*3+2])
                     - c_radii[c1] * c_radii[c1];
                d2 = ray_sphere_dist_fused(ox, oy, oz, dx, dy, dz,
                         c_centers[c2*3], c_centers[c2*3+1], c_centers[c2*3+2])
                     - c_radii[c2] * c_radii[c2];
                d3 = ray_sphere_dist_fused(ox, oy, oz, dx, dy, dz,
                         c_centers[c3*3], c_centers[c3*3+1], c_centers[c3*3+2])
                     - c_radii[c3] * c_radii[c3];
            }

            float best_dist;
            int best_k;
            argmin4(d0, d1, d2, d3, best_dist, best_k);
            int best_child = first_child + best_k;

            if (tid == 0) {
                out_path[sample * BVH_LEVELS + level] = best_child;
            }

            apply_portal_parallel(ox, oy, oz, dx, dy, dz, best_child, tid);
            snell_refract_parallel(spec_a, spec_b, tid, best_child, confidence, best_dist);
            current_node = best_child;
        }

        int expert_idx = current_node - BVH_LEAF_OFFSET;
        if (tid == 0) {
            out_expert[sample] = expert_idx;
            out_confidence[sample] = confidence;
        }

        {
            int leaf0 = tid;
            int leaf1 = tid + WARP_SZ;
            int node0 = BVH_LEAF_OFFSET + leaf0;
            int node1 = BVH_LEAF_OFFSET + leaf1;

            float dist0 = ray_sphere_dist_fused(orig_ox, orig_oy, orig_oz,
                               orig_dx, orig_dy, orig_dz,
                               c_centers[node0*3], c_centers[node0*3+1], c_centers[node0*3+2]);
            float dist1 = ray_sphere_dist_fused(orig_ox, orig_oy, orig_oz,
                               orig_dx, orig_dy, orig_dz,
                               c_centers[node1*3], c_centers[node1*3+1], c_centers[node1*3+2]);

            out_scores[sample * BVH_LEAVES + leaf0] = __expf(-dist0);
            out_scores[sample * BVH_LEAVES + leaf1] = __expf(-dist1);
        }
    }

    // =========================================================================
    // extern "C" launcher stubs
    // =========================================================================

    extern "C" {

    void launch_upload_tree(
        const float* centers,
        const float* radii,
        const float* portals,
        const float* snell_w,
        const float* snell_b
    ) {
        cudaMemcpyToSymbol(c_centers, centers, BVH_NODES * 3 * sizeof(float));
        cudaMemcpyToSymbol(c_radii,   radii,   BVH_NODES * sizeof(float));
        cudaMemcpyToSymbol(c_portals, portals,  BVH_NODES * PORTAL_SIZE * sizeof(float));
        cudaMemcpyToSymbol(c_snell_w, snell_w,  BVH_NODES * SPEC_DIM * sizeof(float));
        cudaMemcpyToSymbol(c_snell_b, snell_b,  BVH_NODES * sizeof(float));
    }

    void launch_route(
        const float* ray_origins,
        const float* ray_directions,
        const float* ray_spectral,
        int*   out_expert,
        float* out_scores,
        int*   out_path,
        float* out_confidence,
        int    batch_size,
        cudaStream_t stream
    ) {
        bvh_router_fused_kernel<<<batch_size, WARP_SZ, 0, stream>>>(
            ray_origins, ray_directions, ray_spectral,
            out_expert, out_scores, out_path, out_confidence,
            batch_size
        );
    }

    } // extern "C"
""").lstrip()

WRAPPER_CPP_SOURCE = textwrap.dedent(r"""
    /*
     * bvh_pybind_wrapper.cpp
     * AUTO-GENERATED by build_bvh_ext_win.py — DO NOT EDIT
     *
     * PyTorch + pybind11 wrapper. Compiled with MSVC, NOT nvcc.
     * Calls the extern "C" CUDA launchers from bvh_kernels_only.cu.
     */

    #define NOMINMAX
    #include <torch/extension.h>
    #include <ATen/cuda/CUDAContext.h>
    #include <c10/cuda/CUDAStream.h>
    #include <cuda_runtime.h>
    #include <stdint.h>

    #define BVH_LEVELS   3
    #define BVH_LEAVES  64
    #define BVH_NODES   85
    #define SPEC_DIM    64
    #define PORTAL_SIZE 12
    #define MAX_BATCH  1024

    // =========================================================================
    // Forward declarations: extern "C" CUDA launchers
    // =========================================================================

    extern "C" {

    void launch_upload_tree(
        const float* centers,
        const float* radii,
        const float* portals,
        const float* snell_w,
        const float* snell_b
    );

    void launch_route(
        const float* ray_origins,
        const float* ray_directions,
        const float* ray_spectral,
        int*   out_expert,
        float* out_scores,
        int*   out_path,
        float* out_confidence,
        int    batch_size,
        cudaStream_t stream
    );

    } // extern "C"

    // =========================================================================
    // Host: Upload BVH tree to constant memory
    // =========================================================================

    void upload_tree_impl(
        torch::Tensor centers,
        torch::Tensor radii,
        torch::Tensor portals,
        torch::Tensor snell_w,
        torch::Tensor snell_b
    ) {
        TORCH_CHECK(centers.is_cpu() && centers.is_contiguous() && centers.dtype() == torch::kFloat32,
            "centers: CPU contiguous float32 [85, 3]");
        TORCH_CHECK(radii.is_cpu() && radii.is_contiguous() && radii.dtype() == torch::kFloat32,
            "radii: CPU contiguous float32 [85]");
        TORCH_CHECK(portals.is_cpu() && portals.is_contiguous() && portals.dtype() == torch::kFloat32,
            "portals: CPU contiguous float32 [85, 12]");
        TORCH_CHECK(snell_w.is_cpu() && snell_w.is_contiguous() && snell_w.dtype() == torch::kFloat32,
            "snell_w: CPU contiguous float32 [85, 64]");
        TORCH_CHECK(snell_b.is_cpu() && snell_b.is_contiguous() && snell_b.dtype() == torch::kFloat32,
            "snell_b: CPU contiguous float32 [85]");

        launch_upload_tree(
            centers.data_ptr<float>(),
            radii.data_ptr<float>(),
            portals.data_ptr<float>(),
            snell_w.data_ptr<float>(),
            snell_b.data_ptr<float>()
        );

        cudaError_t err = cudaGetLastError();
        TORCH_CHECK(err == cudaSuccess, "upload_tree failed: ", cudaGetErrorString(err));
    }

    // =========================================================================
    // Host: Route — Zero-Copy
    // =========================================================================

    std::tuple<torch::Tensor, torch::Tensor, torch::Tensor, torch::Tensor> route_impl(
        torch::Tensor ray_origins,
        torch::Tensor ray_directions,
        torch::Tensor ray_spectral
    ) {
        TORCH_CHECK(ray_origins.is_cuda() && ray_origins.is_contiguous(),
            "ray_origins: CUDA contiguous float32 [batch, 3]");
        TORCH_CHECK(ray_directions.is_cuda() && ray_directions.is_contiguous(),
            "ray_directions: CUDA contiguous float32 [batch, 3]");
        TORCH_CHECK(ray_spectral.is_cuda() && ray_spectral.is_contiguous(),
            "ray_spectral: CUDA contiguous float32 [batch, 64]");

        const int batch_size = (int)ray_origins.size(0);
        TORCH_CHECK(batch_size > 0 && batch_size <= MAX_BATCH,
            "batch_size must be in [1, ", MAX_BATCH, "], got ", batch_size);

        auto device = ray_origins.device();

        auto expert_ids = torch::empty({batch_size}, torch::dtype(torch::kInt32).device(device));
        auto scores     = torch::empty({batch_size, BVH_LEAVES}, torch::dtype(torch::kFloat32).device(device));
        auto confidence = torch::empty({batch_size}, torch::dtype(torch::kFloat32).device(device));
        auto path       = torch::empty({batch_size, BVH_LEVELS}, torch::dtype(torch::kInt32).device(device));

        cudaStream_t stream = at::cuda::getCurrentCUDAStream().stream();

        launch_route(
            ray_origins.data_ptr<float>(),
            ray_directions.data_ptr<float>(),
            ray_spectral.data_ptr<float>(),
            expert_ids.data_ptr<int>(),
            scores.data_ptr<float>(),
            path.data_ptr<int>(),
            confidence.data_ptr<float>(),
            batch_size,
            stream
        );

        cudaError_t err = cudaGetLastError();
        TORCH_CHECK(err == cudaSuccess,
            "BVH kernel launch failed: ", cudaGetErrorString(err));

        return std::make_tuple(expert_ids, scores, confidence, path);
    }

    // =========================================================================
    // Host: Route sync (for benchmarks)
    // =========================================================================

    std::tuple<torch::Tensor, torch::Tensor, torch::Tensor, torch::Tensor> route_sync_impl(
        torch::Tensor ray_origins,
        torch::Tensor ray_directions,
        torch::Tensor ray_spectral
    ) {
        auto result = route_impl(ray_origins, ray_directions, ray_spectral);
        cudaDeviceSynchronize();
        return result;
    }

    // =========================================================================
    // pybind11: register module
    // =========================================================================

    PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
        m.doc() = "SpectralAI BVH Router -- PyTorch Extension Zero-Copy "
                  "(split-build, CUDA 13.2 + PyTorch 2.11 compatible)";

        m.def("upload_tree", &upload_tree_impl,
              "Upload BVH tree to GPU constant memory (CPU tensors)",
              py::arg("centers"), py::arg("radii"), py::arg("portals"),
              py::arg("snell_w"), py::arg("snell_b"));

        m.def("route", &route_impl,
              "BVH routing zero-copy (CUDA tensors). Returns (expert_ids, scores, confidence, path)",
              py::arg("ray_origins"), py::arg("ray_directions"), py::arg("ray_spectral"));

        m.def("route_sync", &route_sync_impl,
              "BVH routing sync for benchmarks (forces cudaDeviceSynchronize)",
              py::arg("ray_origins"), py::arg("ray_directions"), py::arg("ray_spectral"));
    }
""").lstrip()

# =============================================================================
# Helper: run command inside vcvarsall environment
# =============================================================================

def run_with_msvc(args: list[str], description: str) -> None:
    def quote(s: str) -> str:
        return f'"{s}"' if " " in s else s
    inner = " ".join(quote(str(a)) for a in args)
    cmd = f'cmd.exe /C ""{VCVARSALL}" amd64 && {inner}"'
    print(f"\n--- {description} ---")
    print(f"CMD: {cmd}\n")
    result = subprocess.run(cmd, shell=True)
    if result.returncode != 0:
        print(f"\n[FAILED] {description} (exit code {result.returncode})")
        sys.exit(result.returncode)
    print(f"[OK] {description}")


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    print("=" * 70)
    print("  SpectralAI BVH Router — Split Build for Windows")
    print("  CUDA 13.2 CCCL / PyTorch 2.11 cu128 header isolation")
    print("=" * 70)

    # Validate paths
    missing = []
    for label, path in [
        ("vcvarsall.bat", VCVARSALL),
        ("nvcc.exe",      str(NVCC)),
        ("CUDA include",  str(CUDA_INC)),
        ("PyTorch include", str(TORCH_INC)),
        ("Python include",  str(PYTHON_INC)),
    ]:
        if not Path(path).exists():
            missing.append(f"  {label}: {path}")
    if missing:
        print("\n[ERROR] Missing paths:")
        for m in missing:
            print(m)
        sys.exit(1)

    # Stage 0: Write sources
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    print(f"\n[STAGE 0] Writing generated sources to {BUILD_DIR}")
    KERNELS_CU.write_text(KERNELS_CU_SOURCE, encoding="utf-8")
    print(f"  Wrote: {KERNELS_CU}")
    WRAPPER_CPP.write_text(WRAPPER_CPP_SOURCE, encoding="utf-8")
    print(f"  Wrote: {WRAPPER_CPP}")

    # Stage 1: nvcc compiles CUDA kernels
    print("\n[STAGE 1] nvcc: compile BVH kernel (no PyTorch headers)")
    nvcc_cmd = [
        str(NVCC),
        str(KERNELS_CU),
        "-c",
        "-o", str(KERNELS_OBJ),
        "--generate-code", f"arch={COMPUTE_ARCH},code={SM_ARCH}",
        "-Xcompiler", "/EHsc",
        "-Xcompiler", "/MD",
        "-Xcompiler", "/O2",
        "-DCCCL_IGNORE_MSVC_TRADITIONAL_PREPROCESSOR_WARNING",
        "--keep-device-functions",
        "-I", str(CUDA_INC),
        "-std=c++17",
        "--extended-lambda",
        "-lineinfo",
    ]
    run_with_msvc(nvcc_cmd, "nvcc: bvh_kernels_only.cu -> .obj")

    # Stage 2: MSVC compiles pybind11 wrapper
    print("\n[STAGE 2] MSVC: compile pybind11 wrapper (no nvcc)")
    includes = [
        f"/I{PYTHON_INC}",
        f"/I{TORCH_INC}",
        f"/I{TORCH_INC_TH}",
        f"/I{CUDA_INC}",
        f"/I{Path(TORCH_HOME) / 'include' / 'TH'}",
        f"/I{Path(TORCH_HOME) / 'include' / 'THC'}",
    ]
    defines = [
        "/DTORCH_API_INCLUDE_EXTENSION_H",
        "/DTORCH_EXTENSION_NAME=bvh_router_ext",
        "/D_GLIBCXX_USE_CXX11_ABI=0",
        "/DNOMINMAX",
        "/D_USE_MATH_DEFINES",
    ]
    msvc_cmd = [
        "cl.exe", "/nologo", "/EHsc", "/MD", "/O2", "/std:c++17",
        "/Zc:preprocessor", "/W3", "/wd4100", "/wd4127", "/wd4244",
        *includes, *defines,
        "/c", str(WRAPPER_CPP), f"/Fo{WRAPPER_OBJ}",
    ]
    run_with_msvc(msvc_cmd, "cl.exe: bvh_pybind_wrapper.cpp -> .obj")

    # Stage 3: Link
    print("\n[STAGE 3] link.exe: .obj + .obj -> .pyd")
    torch_libs = [
        str(TORCH_LIB / "torch.lib"),
        str(TORCH_LIB / "torch_cpu.lib"),
        str(TORCH_LIB / "torch_cuda.lib"),
        str(TORCH_LIB / "torch_python.lib"),
        str(TORCH_LIB / "c10.lib"),
        str(TORCH_LIB / "c10_cuda.lib"),
    ]
    torch_libs = [l for l in torch_libs if Path(l).exists()]

    cuda_libs = [
        str(Path(CUDA_HOME) / "lib" / "x64" / "cuda.lib"),
        str(Path(CUDA_HOME) / "lib" / "x64" / "cudart.lib"),
    ]
    cuda_libs = [l for l in cuda_libs if Path(l).exists()]

    python_lib_name = f"python{sys.version_info.major}{sys.version_info.minor}.lib"
    python_lib = str(PYTHON_LIB / python_lib_name)

    link_cmd = [
        "link.exe", "/nologo", "/DLL",
        f"/OUT:{PYD_OUT}",
        f"/LIBPATH:{TORCH_LIB}",
        f"/LIBPATH:{PYTHON_LIB}",
        f"/LIBPATH:{Path(CUDA_HOME) / 'lib' / 'x64'}",
        str(KERNELS_OBJ), str(WRAPPER_OBJ),
        *torch_libs, *cuda_libs, python_lib,
        "kernel32.lib", "user32.lib", "advapi32.lib",
        "/SUBSYSTEM:WINDOWS", "/MACHINE:X64",
    ]
    run_with_msvc(link_cmd, f"link.exe: -> {PYD_OUT.name}")

    # Verify
    if PYD_OUT.exists():
        size_kb = PYD_OUT.stat().st_size // 1024
        print(f"\n{'=' * 70}")
        print(f"  BUILD SUCCESS")
        print(f"  Output: {PYD_OUT}  ({size_kb} KB)")
        print(f"{'=' * 70}")
    else:
        print("\n[ERROR] .pyd not found after link step.")
        sys.exit(1)


if __name__ == "__main__":
    main()
