"""
build_ternary_ext_win.py — Two-stage split build for ternary_expert_ext.pyd

Resolves CUDA 13.2 CCCL vs PyTorch 2.11 cu128 header namespace conflicts on Windows:
  Stage 1: nvcc compiles CUDA kernels into .obj — zero PyTorch headers
  Stage 2: MSVC compiles pybind11 wrapper into .obj — zero nvcc
  Stage 3: MSVC links both .obj files into ternary_expert_ext.pyd

Environment assumptions (edit the PATHS section below if needed):
  - MSVC 2024 / VS BuildTools 18
  - CUDA 13.2
  - PyTorch 2.11 cu128
  - Python 3.14
  - RTX 5070 Ti → sm_120 / compute_120
"""

import os
import sys
import subprocess
import textwrap
import shutil
from pathlib import Path

# =============================================================================
# PATHS — edit these if your installation differs
# =============================================================================

VCVARSALL    = r"C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"
CUDA_HOME    = r"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.2"
TORCH_HOME   = r"C:\Users\jsilv\AppData\Roaming\Python\Python314\site-packages\torch"
PYTHON_HOME  = r"C:\Python314"
SM_ARCH      = "sm_120"
COMPUTE_ARCH = "compute_120"

# Output module name (without .pyd)
EXT_NAME = "ternary_expert_ext"

# =============================================================================
# Derived paths
# =============================================================================

SCRIPT_DIR   = Path(__file__).parent.resolve()
BUILD_DIR    = SCRIPT_DIR / "build_ternary"
NVCC         = Path(CUDA_HOME) / "bin" / "nvcc.exe"

PYTHON_INC   = Path(PYTHON_HOME) / "include"
TORCH_INC    = Path(TORCH_HOME) / "include"
TORCH_INC_TH = Path(TORCH_HOME) / "include" / "torch" / "csrc" / "api" / "include"
CUDA_INC     = Path(CUDA_HOME) / "include"

# PyTorch libs needed for linking
TORCH_LIB    = Path(TORCH_HOME) / "lib"

# Python lib
PYTHON_LIB   = Path(PYTHON_HOME) / "libs"

# =============================================================================
# Generated file paths
# =============================================================================

KERNELS_CU   = BUILD_DIR / "ternary_kernels_only.cu"
WRAPPER_CPP  = BUILD_DIR / "ternary_pybind_wrapper.cpp"
KERNELS_OBJ  = BUILD_DIR / "ternary_kernels_only.obj"
WRAPPER_OBJ  = BUILD_DIR / "ternary_pybind_wrapper.obj"
PYD_OUT      = SCRIPT_DIR / f"{EXT_NAME}.pyd"

# =============================================================================
# Stage 0: Generate the two source files
# =============================================================================

KERNELS_CU_SOURCE = textwrap.dedent(r"""
    /*
     * ternary_kernels_only.cu
     * AUTO-GENERATED by build_ternary_ext_win.py — DO NOT EDIT
     *
     * Pure CUDA file: NO PyTorch headers, NO pybind11.
     * Exports extern "C" launcher functions that the pybind11 wrapper calls.
     *
     * This isolation avoids CUDA 13.2 CCCL / PyTorch 2.11 cu128 header
     * namespace conflicts (thrust ambiguity, /Zc:preprocessor 'std' issues).
     */

    #include <cuda_runtime.h>
    #include <stdint.h>

    #define TERN_PACK 16
    #define TERN_MASK 3u
    #define TERN_POS  1u
    #define TERN_NEG  2u
    #define BLOCK_SIZE 256

    // =========================================================================
    // Device: ternary dot product for 16 packed weights
    // =========================================================================

    __device__ __forceinline__ float ternary_dot_16(
        uint32_t packed,
        const float* __restrict__ input,
        int stride
    ) {
        float acc = 0.0f;
        #pragma unroll
        for (int i = 0; i < TERN_PACK; i++) {
            uint32_t code = (packed >> (i * 2)) & TERN_MASK;
            float val = input[i * stride];
            float sign = (float)(code == TERN_POS) - (float)(code >> 1);
            acc = __fmaf_rn(sign, val, acc);
        }
        return acc;
    }

    // =========================================================================
    // Kernel: Ternary Linear
    // =========================================================================

    __global__ void ternary_linear_kernel(
        const float* __restrict__    input,
        const uint32_t* __restrict__ packed,
        const float* __restrict__    scale,
        const float* __restrict__    bias,
        float* __restrict__          output,
        int batch_size,
        int in_dim,
        int out_dim,
        int packed_rows,
        int has_bias
    ) {
        const int sample = blockIdx.x;
        if (sample >= batch_size) return;

        const float* inp = &input[sample * in_dim];
        float* out = &output[sample * out_dim];

        for (int col = threadIdx.x; col < out_dim; col += blockDim.x) {
            float acc = 0.0f;

            for (int pr = 0; pr < packed_rows; pr++) {
                uint32_t p = __ldg(&packed[pr * out_dim + col]);
                acc += ternary_dot_16(p, &inp[pr * TERN_PACK], 1);
            }

            acc *= __ldg(&scale[col]);

            if (has_bias) {
                acc += __ldg(&bias[col]);
            }

            out[col] = acc;
        }
    }

    // =========================================================================
    // Kernel: Ternary Gated MLP (gate * up -> SiLU -> down)
    // =========================================================================

    __global__ void ternary_gated_mlp_kernel(
        const float* __restrict__    input,
        const uint32_t* __restrict__ gate_packed,
        const uint32_t* __restrict__ up_packed,
        const uint32_t* __restrict__ down_packed,
        const float* __restrict__    gate_scale,
        const float* __restrict__    up_scale,
        const float* __restrict__    down_scale,
        float* __restrict__          output,
        int batch_size,
        int in_dim,
        int intermediate_dim,
        int out_dim,
        int packed_in_rows,
        int packed_inter_rows
    ) {
        extern __shared__ float smem[];

        const int sample = blockIdx.x;
        if (sample >= batch_size) return;

        float* s_input  = smem;
        float* s_hidden = smem + in_dim;

        const float* inp = &input[sample * in_dim];
        float* out = &output[sample * out_dim];

        for (int i = threadIdx.x; i < in_dim; i += blockDim.x) {
            s_input[i] = __ldg(&inp[i]);
        }
        __syncthreads();

        // Gate + Up + SiLU gating
        for (int col = threadIdx.x; col < intermediate_dim; col += blockDim.x) {
            float gate_acc = 0.0f;
            float up_acc   = 0.0f;

            for (int pr = 0; pr < packed_in_rows; pr++) {
                uint32_t gp = __ldg(&gate_packed[pr * intermediate_dim + col]);
                uint32_t up = __ldg(&up_packed[pr * intermediate_dim + col]);
                gate_acc += ternary_dot_16(gp, &s_input[pr * TERN_PACK], 1);
                up_acc   += ternary_dot_16(up, &s_input[pr * TERN_PACK], 1);
            }

            gate_acc *= __ldg(&gate_scale[col]);
            up_acc   *= __ldg(&up_scale[col]);

            float silu_gate = gate_acc / (1.0f + __expf(-gate_acc));
            s_hidden[col] = silu_gate * up_acc;
        }
        __syncthreads();

        // Down projection
        for (int col = threadIdx.x; col < out_dim; col += blockDim.x) {
            float acc = 0.0f;

            for (int pr = 0; pr < packed_inter_rows; pr++) {
                uint32_t dp = __ldg(&down_packed[pr * out_dim + col]);
                acc += ternary_dot_16(dp, &s_hidden[pr * TERN_PACK], 1);
            }

            acc *= __ldg(&down_scale[col]);
            out[col] = acc;
        }
    }

    // =========================================================================
    // extern "C" launcher stubs — called from the pybind11 wrapper
    // Raw pointer API: no PyTorch types, no CCCL headers beyond cuda_runtime.h
    // =========================================================================

    extern "C" {

    void launch_ternary_linear(
        const float*    input,
        const uint32_t* packed,
        const float*    scale,
        const float*    bias,       // may be nullptr
        float*          output,
        int batch_size,
        int in_dim,
        int out_dim,
        int packed_rows,
        int has_bias,
        cudaStream_t    stream
    ) {
        int threads = batch_size > 0 ? max(min(out_dim, BLOCK_SIZE), 32) : 32;
        ternary_linear_kernel<<<batch_size, threads, 0, stream>>>(
            input, packed, scale, bias, output,
            batch_size, in_dim, out_dim, packed_rows, has_bias
        );
    }

    void launch_ternary_gated_mlp(
        const float*    input,
        const uint32_t* gate_packed,
        const uint32_t* up_packed,
        const uint32_t* down_packed,
        const float*    gate_scale,
        const float*    up_scale,
        const float*    down_scale,
        float*          output,
        int batch_size,
        int in_dim,
        int intermediate_dim,
        int out_dim,
        int packed_in_rows,
        int packed_inter_rows,
        size_t smem_bytes,
        cudaStream_t stream
    ) {
        int max_dim = intermediate_dim > out_dim ? intermediate_dim : out_dim;
        int threads = max_dim < 1024 ? max_dim : 1024;
        ternary_gated_mlp_kernel<<<batch_size, threads, smem_bytes, stream>>>(
            input, gate_packed, up_packed, down_packed,
            gate_scale, up_scale, down_scale, output,
            batch_size, in_dim, intermediate_dim, out_dim,
            packed_in_rows, packed_inter_rows
        );
    }

    } // extern "C"
""").lstrip()

WRAPPER_CPP_SOURCE = textwrap.dedent(r"""
    /*
     * ternary_pybind_wrapper.cpp
     * AUTO-GENERATED by build_ternary_ext_win.py — DO NOT EDIT
     *
     * PyTorch + pybind11 wrapper. Compiled with MSVC, NOT nvcc.
     * Calls the extern "C" CUDA launchers from ternary_kernels_only.cu.
     *
     * This separation avoids CUDA 13.2 CCCL / PyTorch cu128 header conflicts.
     */

    // Must come before any Windows headers to avoid min/max macro conflicts
    #define NOMINMAX

    #include <torch/extension.h>
    #include <ATen/cuda/CUDAContext.h>
    #include <c10/cuda/CUDAStream.h>
    #include <cuda_runtime.h>
    #include <stdint.h>
    #include <stddef.h>

    #define TERN_PACK 16
    #define TERN_POS  1u
    #define TERN_NEG  2u

    // =========================================================================
    // Forward declarations: extern "C" CUDA launchers from ternary_kernels_only.obj
    // =========================================================================

    extern "C" {

    void launch_ternary_linear(
        const float*    input,
        const uint32_t* packed,
        const float*    scale,
        const float*    bias,
        float*          output,
        int batch_size,
        int in_dim,
        int out_dim,
        int packed_rows,
        int has_bias,
        cudaStream_t    stream
    );

    void launch_ternary_gated_mlp(
        const float*    input,
        const uint32_t* gate_packed,
        const uint32_t* up_packed,
        const uint32_t* down_packed,
        const float*    gate_scale,
        const float*    up_scale,
        const float*    down_scale,
        float*          output,
        int batch_size,
        int in_dim,
        int intermediate_dim,
        int out_dim,
        int packed_in_rows,
        int packed_inter_rows,
        size_t smem_bytes,
        cudaStream_t stream
    );

    } // extern "C"

    // =========================================================================
    // Host: Pack ternary weights (CPU, no CUDA needed)
    // =========================================================================

    torch::Tensor pack_ternary_impl(torch::Tensor weights_int8) {
        TORCH_CHECK(weights_int8.is_cpu() && weights_int8.dtype() == torch::kInt8,
            "pack_ternary: weights must be CPU int8 tensor");

        auto weights = weights_int8.contiguous();
        int rows        = (int)weights.size(0);
        int cols        = (int)weights.size(1);
        int packed_rows = (rows + TERN_PACK - 1) / TERN_PACK;

        auto packed = torch::zeros({packed_rows, cols},
                          torch::dtype(torch::kInt32));
        const auto* w_ptr = weights.data_ptr<int8_t>();
        auto*       p_ptr = packed.data_ptr<int32_t>();

        for (int pr = 0; pr < packed_rows; pr++) {
            for (int c = 0; c < cols; c++) {
                uint32_t pack = 0u;
                for (int i = 0; i < TERN_PACK; i++) {
                    int row = pr * TERN_PACK + i;
                    if (row >= rows) break;

                    int8_t val = w_ptr[row * cols + c];
                    uint32_t code;
                    if (val > 0)       code = TERN_POS;
                    else if (val < 0)  code = TERN_NEG;
                    else               code = 0u;

                    pack |= (code << (i * 2));
                }
                p_ptr[pr * cols + c] = static_cast<int32_t>(pack);
            }
        }

        return packed;
    }

    // =========================================================================
    // Host: Ternary Linear forward
    // =========================================================================

    torch::Tensor ternary_linear_impl(
        torch::Tensor input,
        torch::Tensor packed_weights,
        torch::Tensor scale,
        c10::optional<torch::Tensor> bias
    ) {
        TORCH_CHECK(input.is_cuda() && input.is_contiguous(),
            "ternary_linear: input must be CUDA contiguous float32");
        TORCH_CHECK(packed_weights.is_cuda() && packed_weights.is_contiguous(),
            "ternary_linear: packed_weights must be CUDA contiguous int32");
        TORCH_CHECK(scale.is_cuda() && scale.is_contiguous(),
            "ternary_linear: scale must be CUDA contiguous float32");

        int batch       = (int)input.size(0);
        int in_dim      = (int)input.size(1);
        int packed_rows = (int)packed_weights.size(0);
        int out_dim     = (int)packed_weights.size(1);

        auto output = torch::empty({batch, out_dim},
            torch::dtype(torch::kFloat32).device(input.device()));

        int        has_bias  = bias.has_value() ? 1 : 0;
        const float* bias_ptr = has_bias ? bias.value().data_ptr<float>() : nullptr;

        cudaStream_t stream = at::cuda::getCurrentCUDAStream().stream();

        launch_ternary_linear(
            input.data_ptr<float>(),
            reinterpret_cast<const uint32_t*>(packed_weights.data_ptr<int32_t>()),
            scale.data_ptr<float>(),
            bias_ptr,
            output.data_ptr<float>(),
            batch, in_dim, out_dim, packed_rows, has_bias,
            stream
        );

        cudaError_t err = cudaGetLastError();
        TORCH_CHECK(err == cudaSuccess,
            "ternary_linear kernel failed: ", cudaGetErrorString(err));

        return output;
    }

    // =========================================================================
    // Host: Ternary Gated MLP forward
    // =========================================================================

    torch::Tensor ternary_gated_mlp_impl(
        torch::Tensor input,
        torch::Tensor gate_packed,
        torch::Tensor up_packed,
        torch::Tensor down_packed,
        torch::Tensor gate_scale,
        torch::Tensor up_scale,
        torch::Tensor down_scale
    ) {
        TORCH_CHECK(input.is_cuda() && input.is_contiguous(),
            "ternary_gated_mlp: input must be CUDA contiguous float32");

        int batch            = (int)input.size(0);
        int in_dim           = (int)input.size(1);
        int intermediate_dim = (int)gate_packed.size(1);
        int out_dim          = (int)down_packed.size(1);
        int packed_in_rows   = (int)gate_packed.size(0);
        int packed_inter_rows = (int)down_packed.size(0);

        auto output = torch::empty({batch, out_dim},
            torch::dtype(torch::kFloat32).device(input.device()));

        size_t smem_bytes = (size_t)(in_dim + intermediate_dim) * sizeof(float);

        // Guard: shared memory limit
        int device_id = (int)input.device().index();
        int max_smem  = 0;
        cudaDeviceGetAttribute(&max_smem, cudaDevAttrMaxSharedMemoryPerBlock, device_id);
        TORCH_CHECK(smem_bytes <= (size_t)max_smem,
            "ternary_gated_mlp: shared memory ", smem_bytes,
            " bytes exceeds device max ", max_smem,
            " bytes. Reduce in_dim (", in_dim,
            ") or intermediate_dim (", intermediate_dim, ").");

        cudaStream_t stream = at::cuda::getCurrentCUDAStream().stream();

        launch_ternary_gated_mlp(
            input.data_ptr<float>(),
            reinterpret_cast<const uint32_t*>(gate_packed.data_ptr<int32_t>()),
            reinterpret_cast<const uint32_t*>(up_packed.data_ptr<int32_t>()),
            reinterpret_cast<const uint32_t*>(down_packed.data_ptr<int32_t>()),
            gate_scale.data_ptr<float>(),
            up_scale.data_ptr<float>(),
            down_scale.data_ptr<float>(),
            output.data_ptr<float>(),
            batch, in_dim, intermediate_dim, out_dim,
            packed_in_rows, packed_inter_rows,
            smem_bytes,
            stream
        );

        cudaError_t err = cudaGetLastError();
        TORCH_CHECK(err == cudaSuccess,
            "ternary_gated_mlp kernel failed: ", cudaGetErrorString(err));

        return output;
    }

    // =========================================================================
    // pybind11: register module
    // =========================================================================

    PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
        m.doc() = "SpectralAI Ternary Expert — split-build PyTorch Extension "
                  "(arbitrary dimensions, zero multiplications, CUDA 13.2 + PyTorch 2.11 compatible)";

        m.def("pack_ternary", &pack_ternary_impl,
              "Pack int8 ternary weights {-1,0,+1} to uint32 (16 per uint32)",
              py::arg("weights_int8"));

        m.def("ternary_linear", &ternary_linear_impl,
              "Ternary matrix multiply: no FP multiplications, only add/sub/skip",
              py::arg("input"), py::arg("packed_weights"), py::arg("scale"),
              py::arg("bias") = c10::nullopt);

        m.def("ternary_gated_mlp", &ternary_gated_mlp_impl,
              "Fused ternary gated MLP: gate(SiLU)*up -> down, zero multiplications",
              py::arg("input"), py::arg("gate_packed"), py::arg("up_packed"),
              py::arg("down_packed"), py::arg("gate_scale"), py::arg("up_scale"),
              py::arg("down_scale"));
    }
""").lstrip()

# =============================================================================
# Helper: run a command inside a vcvarsall-initialized environment
# =============================================================================

def run_with_msvc(args: list[str], description: str) -> None:
    """
    Wraps a command in a cmd.exe call that first sources vcvarsall.bat (x64)
    so that cl.exe, link.exe and their libraries are on PATH.
    """
    # Escape each arg for cmd.exe: wrap in double quotes if it contains spaces
    def quote(s: str) -> str:
        return f'"{s}"' if " " in s else s

    inner = " ".join(quote(str(a)) for a in args)
    cmd = f'cmd.exe /C ""{VCVARSALL}" amd64 && {inner}"'

    print(f"\n--- {description} ---")
    print(f"CMD: {cmd}\n")

    result = subprocess.run(cmd, shell=True)
    if result.returncode != 0:
        print(f"\n[FAILED] {description} (exit code {result.returncode})")
        sys.exit(result.returncode)
    print(f"[OK] {description}")


def run(args: list[str], description: str) -> None:
    """Run a command directly (for nvcc which doesn't need vcvarsall when PATH is set)."""
    cmd = " ".join(f'"{str(a)}"' if " " in str(a) else str(a) for a in args)
    print(f"\n--- {description} ---")
    print(f"CMD: {cmd}\n")

    result = subprocess.run(cmd, shell=True)
    if result.returncode != 0:
        print(f"\n[FAILED] {description} (exit code {result.returncode})")
        sys.exit(result.returncode)
    print(f"[OK] {description}")


# =============================================================================
# Main build procedure
# =============================================================================

def main() -> None:
    print("=" * 70)
    print("  SpectralAI Ternary Expert — Split Build for Windows")
    print("  CUDA 13.2 CCCL / PyTorch 2.11 cu128 header isolation")
    print("=" * 70)

    # -------------------------------------------------------------------------
    # 0. Validate paths
    # -------------------------------------------------------------------------
    missing = []
    for label, path in [
        ("vcvarsall.bat", VCVARSALL),
        ("nvcc.exe",      str(NVCC)),
        ("CUDA include",  str(CUDA_INC)),
        ("PyTorch include", str(TORCH_INC)),
        ("Python include",  str(PYTHON_INC)),
    ]:
        if not Path(path).exists():
            missing.append(f"  {label}: {path}")

    if missing:
        print("\n[ERROR] The following required paths were not found:")
        for m in missing:
            print(m)
        print("\nEdit the PATHS section at the top of this script.")
        sys.exit(1)

    # -------------------------------------------------------------------------
    # 1. Create build directory and write generated sources
    # -------------------------------------------------------------------------
    BUILD_DIR.mkdir(parents=True, exist_ok=True)

    print(f"\n[STAGE 0] Writing generated sources to {BUILD_DIR}")
    KERNELS_CU.write_text(KERNELS_CU_SOURCE, encoding="utf-8")
    print(f"  Wrote: {KERNELS_CU}")
    WRAPPER_CPP.write_text(WRAPPER_CPP_SOURCE, encoding="utf-8")
    print(f"  Wrote: {WRAPPER_CPP}")

    # -------------------------------------------------------------------------
    # 2. Stage 1: nvcc compiles CUDA kernels → .obj
    #    No PyTorch headers. Use -DCCCL_IGNORE_MSVC_TRADITIONAL_PREPROCESSOR_WARNING
    #    to suppress the CCCL warning about /Zc:preprocessor.
    #    We compile device code only (no linking), producing a host+device .obj.
    # -------------------------------------------------------------------------
    print("\n[STAGE 1] nvcc: compile CUDA kernels (no PyTorch headers)")

    # Base nvcc flags — no PyTorch headers involved at all
    # --generate-code is the canonical way to set arch for nvcc; avoid mixing
    # -arch/-code with --generate-code as that can produce duplicate-code warnings.
    nvcc_base_flags = [
        str(NVCC),
        str(KERNELS_CU),
        "-c",                                # compile only, no link
        "-o", str(KERNELS_OBJ),
        "--generate-code", f"arch={COMPUTE_ARCH},code={SM_ARCH}",
        "-Xcompiler", "/EHsc",               # exception handling for MSVC host
        "-Xcompiler", "/MD",                 # match PyTorch's dynamic CRT
        "-Xcompiler", "/O2",
        # Suppress the CCCL warning that fires when /Zc:preprocessor is absent.
        # Our kernel file does NOT include Thrust/CCCL headers so this is safe.
        "-DCCCL_IGNORE_MSVC_TRADITIONAL_PREPROCESSOR_WARNING",
        "--keep-device-functions",           # expose device symbols to linker
        "-I", str(CUDA_INC),
        "-std=c++17",
        "--extended-lambda",
        "-lineinfo",                         # low-overhead debug info for nsight
    ]

    # --no-cuda-headers-in-path prevents nvcc from auto-prepending its own
    # CCCL/Thrust include dirs to the search path.  Available since nvcc ~12.4.
    # We try with it first; if nvcc rejects the flag we retry without it.
    nvcc_cmd_with_flag  = nvcc_base_flags + ["--no-cuda-headers-in-path"]
    nvcc_cmd_without    = nvcc_base_flags  # fallback

    def _try_nvcc(cmd: list[str], desc: str) -> bool:
        """Returns True on success, False on non-zero exit."""
        inner = " ".join(f'"{str(a)}"' if " " in str(a) else str(a) for a in cmd)
        full  = f'cmd.exe /C ""{VCVARSALL}" amd64 && {inner}"'
        print(f"\n--- {desc} ---")
        print(f"CMD: {full}\n")
        rc = subprocess.run(full, shell=True).returncode
        if rc == 0:
            print(f"[OK] {desc}")
        return rc == 0

    ok = _try_nvcc(nvcc_cmd_with_flag,
                   "nvcc: ternary_kernels_only.cu -> .obj (--no-cuda-headers-in-path)")
    if not ok:
        print("[WARN] --no-cuda-headers-in-path rejected by this nvcc — retrying without it")
        if not _try_nvcc(nvcc_cmd_without,
                         "nvcc: ternary_kernels_only.cu -> .obj (fallback)"):
            print("\n[FAILED] nvcc compilation failed on both attempts.")
            sys.exit(1)

    # -------------------------------------------------------------------------
    # 3. Stage 2: MSVC compiles pybind11 wrapper → .obj
    #    No nvcc involved. We include PyTorch + Python + pybind11 headers.
    #    /Zc:preprocessor is required by PyTorch 2.x but conflicts with CCCL —
    #    since we have zero CCCL/Thrust includes here, it is safe.
    # -------------------------------------------------------------------------
    print("\n[STAGE 2] MSVC: compile pybind11 wrapper (no nvcc)")

    # Collect include dirs
    includes = [
        f"/I{PYTHON_INC}",
        f"/I{TORCH_INC}",
        f"/I{TORCH_INC_TH}",
        f"/I{CUDA_INC}",
        f"/I{Path(TORCH_HOME) / 'include' / 'TH'}",
        f"/I{Path(TORCH_HOME) / 'include' / 'THC'}",
    ]

    # PyTorch 2.x requires these defines
    defines = [
        "/DTORCH_API_INCLUDE_EXTENSION_H",
        "/DTORCH_EXTENSION_NAME=ternary_expert_ext",
        "/D_GLIBCXX_USE_CXX11_ABI=0",       # matches PyTorch's ABI
        "/DNOMINMAX",
        "/D_USE_MATH_DEFINES",
    ]

    msvc_compile_cmd = [
        "cl.exe",
        "/nologo",
        "/EHsc",
        "/MD",                               # dynamic CRT (matches PyTorch)
        "/O2",
        "/std:c++17",
        "/Zc:preprocessor",                  # required by PyTorch 2.x headers
        "/W3",
        # Suppress C4100 (unreferenced formal parameter) — common in torch headers
        "/wd4100",
        # Suppress C4127 (conditional expression is constant) — common in torch macros
        "/wd4127",
        # Suppress C4244 (conversion warnings) — common in torch
        "/wd4244",
        *includes,
        *defines,
        "/c",                                # compile only
        str(WRAPPER_CPP),
        f"/Fo{WRAPPER_OBJ}",
    ]

    run_with_msvc(msvc_compile_cmd, "cl.exe: ternary_pybind_wrapper.cpp -> .obj")

    # -------------------------------------------------------------------------
    # 4. Stage 3: Link both .obj files → .pyd
    #    Use MSVC link.exe (not nvcc --link) to avoid re-introducing CCCL.
    # -------------------------------------------------------------------------
    print("\n[STAGE 3] link.exe: .obj + .obj -> .pyd")

    # PyTorch import libraries
    torch_libs = [
        str(TORCH_LIB / "torch.lib"),
        str(TORCH_LIB / "torch_cpu.lib"),
        str(TORCH_LIB / "torch_cuda.lib"),
        str(TORCH_LIB / "torch_python.lib"),
        str(TORCH_LIB / "c10.lib"),
        str(TORCH_LIB / "c10_cuda.lib"),
    ]

    # Filter to only libs that actually exist (torch_cuda.lib may be absent
    # on CPU-only builds, though we require CUDA here)
    torch_libs = [l for l in torch_libs if Path(l).exists()]

    # CUDA import libraries
    cuda_libs = [
        str(Path(CUDA_HOME) / "lib" / "x64" / "cuda.lib"),
        str(Path(CUDA_HOME) / "lib" / "x64" / "cudart.lib"),
    ]
    cuda_libs = [l for l in cuda_libs if Path(l).exists()]

    # Python import library
    python_lib_name = f"python{sys.version_info.major}{sys.version_info.minor}.lib"
    python_lib = str(PYTHON_LIB / python_lib_name)

    # Additional Windows system libs needed by torch
    sys_libs = ["kernel32.lib", "user32.lib", "advapi32.lib"]

    link_cmd = [
        "link.exe",
        "/nologo",
        "/DLL",                              # build a DLL (.pyd is a DLL)
        f"/OUT:{PYD_OUT}",
        f"/LIBPATH:{TORCH_LIB}",
        f"/LIBPATH:{PYTHON_LIB}",
        f"/LIBPATH:{Path(CUDA_HOME) / 'lib' / 'x64'}",
        str(KERNELS_OBJ),
        str(WRAPPER_OBJ),
        *torch_libs,
        *cuda_libs,
        python_lib,
        *sys_libs,
        "/SUBSYSTEM:WINDOWS",
        "/MACHINE:X64",
    ]

    run_with_msvc(link_cmd, f"link.exe: -> {PYD_OUT.name}")

    # -------------------------------------------------------------------------
    # 5. Verify the output
    # -------------------------------------------------------------------------
    if PYD_OUT.exists():
        size_kb = PYD_OUT.stat().st_size // 1024
        print(f"\n{'=' * 70}")
        print(f"  BUILD SUCCESS")
        print(f"  Output: {PYD_OUT}  ({size_kb} KB)")
        print(f"{'=' * 70}")
        print(f"\nTo use from Python:")
        print(f"  import sys")
        print(f'  sys.path.insert(0, r"{SCRIPT_DIR}")')
        print(f"  import {EXT_NAME} as ternary_ext")
        print(f"  # ternary_ext.pack_ternary(...)")
        print(f"  # ternary_ext.ternary_linear(...)")
        print(f"  # ternary_ext.ternary_gated_mlp(...)")
    else:
        print("\n[ERROR] .pyd not found after link step — check output above.")
        sys.exit(1)


if __name__ == "__main__":
    main()
